(defnode start)
(defnode have-5)
(defnode have-10)
(defnode have-15)
(defnode have-20)
(defnode have-25)
(defnode end)

(defarc start nickel have-5 "Clunk!")
(defarc start dime have-10 "Clink!")
(defarc start coin-return start "Nothing to return")
(defarc have-5 nickel have-10 "Clunk!")
(defarc have-5 dime have-15 "Clink!")
(defarc have-5 coin-return start "Returned five cents.")
(defarc have-10 nickel have-15 "Clunk!")
(defarc have-10 dime have-20 "Clink!")
(defarc have-10 coin-return start "Returned 10 cents")
(defarc have-15 nickel have-20 "Clunk!")
(defarc have-15 dime have-25 "Clink!")
(defarc have-15 gum-button end "Vending a stick of gum")
(defarc have-15 coin-return start "Returned 15 cents")
(defarc have-20 nickel have-25 "Clunk!")
(defarc have-20 dime have-20 "You get your dime back")
(defarc have-20 coin-return start "Returned 20 cents")
(defarc have-25 nickel have-25 "You get your nickel back")
(defarc have-25 dime have-25 "You get your dime back")
(defarc have-25 coin-return start "Returned 25 cents")
(defarc have-25 soda-button end "Vending a soda")
